### ISSUE TITLE
Support repeated patterns with individual responses

### ISSUE THREAD

**Issue by lundberg** [lundberg/responsex#6]
It should be possible to add same url or matcher multiple times with same or different responses.

**Example:**
```py
import httpx
import responsex

@responsex.activate()
def test_me():
    responsex.add("POST", "https://foo/bar/", status_code=201)
    responsex.add("POST", "https://foo/bar/", status_code=409)

    response = httpx.post("https://foo/bar/", json={"foo": "bar"})
    assert response.status_code == 201

    response = httpx.post("https://foo/bar/", json={"foo": "bar"})
    assert response.status_code == 409
```

**Comment by puilp0502** [comment]
Hi, is this feature covered in the documentation? I was digging through the documentation wondering whether this feature is supported, but to no avail.
Since this is a common feature for request mocking library (e.g. [responses](https://github.com/getsentry/responses)), A callout at the top of the user guide might help future users.

**Comment by lundberg** [comment]
It sure is supported, but with a bit different api.

The RESPX api is inspired by python mock, so to add add multiple chained responses for a specific pattern/route in `respx` you'll mock with an [iterable side effect](https://lundberg.github.io/respx/guide/#iterable).

Something like...
```py
respx.post("https://example.com/").mock(side_effect=[Response(201), ...])
```

FYI, when you add repeated patterns with the `responses` lib, the responses are chained as you describe, with `respx` this will instead replace the response/route for that pattern.

**Comment by puilp0502** [comment]
@lundberg Ah, that makes sense. Thanks for your quick reply!
